services:
  - type: web
    name: portfolio-agent
    runtime: node
    plan: free
    buildCommand: npm install && npx playwright install --with-deps chromium && ls -la public/
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER
        value: "true"
    autoDeploy: true
    healthCheckPath: /api/health