services:
  - type: web
    name: portfolio-agent
    runtime: docker
    plan: free
    rootDir: .
    autoDeploy: true
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER
        value: "true"